//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyNhanVienEntities : DbContext
    {
        public QuanLyNhanVienEntities()
            : base("name=QuanLyNhanVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_TocKy> T_TocKy { get; set; }
        public virtual DbSet<T_NhanVien> T_NhanVien { get; set; }
        public virtual DbSet<T_KhoaPhong> T_KhoaPhong { get; set; }
        public virtual DbSet<T_PhieuKham> T_PhieuKham { get; set; }
    
        public virtual ObjectResult<P_DanhSachKhoaPhong_Result> P_DanhSachKhoaPhong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_DanhSachKhoaPhong_Result>("P_DanhSachKhoaPhong");
        }
    
        public virtual ObjectResult<P_DanhSachNhanVien_Result> P_DanhSachNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_DanhSachNhanVien_Result>("P_DanhSachNhanVien");
        }
    
        public virtual ObjectResult<P_DanhSachSucKhoeNhanVien_Result> P_DanhSachSucKhoeNhanVien(string namKham)
        {
            var namKhamParameter = namKham != null ?
                new ObjectParameter("NamKham", namKham) :
                new ObjectParameter("NamKham", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_DanhSachSucKhoeNhanVien_Result>("P_DanhSachSucKhoeNhanVien", namKhamParameter);
        }
    }
}
