//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_KhoThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_KhoThietBi()
        {
            this.T_PhieuNhap = new HashSet<T_PhieuNhap>();
            this.T_PhieuLanh = new HashSet<T_PhieuLanh>();
        }
    
        public int MaKho { get; set; }
        public string MaKhoa { get; set; }
        public string TenKho { get; set; }
        public string KyHieu { get; set; }
        public Nullable<int> STT { get; set; }
        public bool IsEnable { get; set; }
    
        public virtual T_KhoaPhong T_KhoaPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PhieuNhap> T_PhieuNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PhieuLanh> T_PhieuLanh { get; set; }
    }
}
