//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PhieuLanh_ChiTiet
    {
        public int ID { get; set; }
        public int MaPhieuLanh { get; set; }
        public int MaThietBi { get; set; }
        public decimal SoLuong { get; set; }
    
        public virtual T_Lib_ThietBi T_Lib_ThietBi { get; set; }
        public virtual T_PhieuLanh T_PhieuLanh { get; set; }
    }
}
