//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PhieuNhap()
        {
            this.T_PhieuNhap_ChiTiet = new HashSet<T_PhieuNhap_ChiTiet>();
        }
    
        public int MaPhieuNhap { get; set; }
        public int MaKho { get; set; }
        public string NhaCungCap { get; set; }
        public string NguoiNhap { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public System.DateTime NgayLuu { get; set; }
        public string GhiChu { get; set; }
        public string SoPhieu { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual T_KhoThietBi T_KhoThietBi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PhieuNhap_ChiTiet> T_PhieuNhap_ChiTiet { get; set; }
    }
}
