//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PhieuKham
    {
        public int MaPhieuKham { get; set; }
        public int MaNhanVien { get; set; }
        public System.DateTime NgayKham { get; set; }
        public string TL_ChieuCao { get; set; }
        public string TL_CanNang { get; set; }
        public string TL_VongNgucTB { get; set; }
        public string TL_ChiSoBMI { get; set; }
        public string TL_Mach { get; set; }
        public string TL_HuyetAp { get; set; }
        public string TL_NhietDo { get; set; }
        public string TL_NhipTho { get; set; }
        public string TL_PhanLoai { get; set; }
        public string TL_BacSi { get; set; }
        public string LS_TuanHoan { get; set; }
        public string LS_TuanHoan_PhanLoai { get; set; }
        public string LS_TuanHoan_BacSi { get; set; }
        public string LS_HoHap { get; set; }
        public string LS_HoHap_PhanLoai { get; set; }
        public string LS_HoHap_BacSi { get; set; }
        public string LS_TieuHoa { get; set; }
        public string LS_TieuHoa_PhanLoai { get; set; }
        public string LS_TieuHoa_BacSi { get; set; }
        public string LS_ThanTietNieu { get; set; }
        public string LS_ThanTietNieu_PhanLoai { get; set; }
        public string LS_ThanTietNieu_BacSi { get; set; }
        public string LS_ThanKinh { get; set; }
        public string LS_ThanKinh_PhanLoai { get; set; }
        public string LS_ThanKinh_BacSi { get; set; }
        public string LS_TamThan { get; set; }
        public string LS_TamThan_PhanLoai { get; set; }
        public string LS_TamThan_BacSi { get; set; }
        public string LS_HeVanDong { get; set; }
        public string LS_HeVanDong_PhanLoai { get; set; }
        public string LS_HeVanDong_BacSi { get; set; }
        public string LS_NoiTiet { get; set; }
        public string LS_NoiTiet_PhanLoai { get; set; }
        public string LS_NoiTiet_BacSi { get; set; }
        public string LS_DaLieu { get; set; }
        public string LS_DaLieu_PhanLoai { get; set; }
        public string LS_DaLieu_BacSi { get; set; }
        public string LS_NgoaiKhoa { get; set; }
        public string LS_NgoaiKhoa_PhanLoai { get; set; }
        public string LS_NgoaiKhoa_BacSiKham { get; set; }
        public string LS_SanPhuKhoa { get; set; }
        public string LS_SanPhuKhoa_PhanLoai { get; set; }
        public string LS_SanPhuKhoa_BacSi { get; set; }
        public string LS_Mat { get; set; }
        public string LS_Mat_PhanLoai { get; set; }
        public string LS_Mat_BacSi { get; set; }
        public string LS_Mat_KhongKinh_MatPhai { get; set; }
        public string LS_Mat_KhongKinh_MatTrai { get; set; }
        public string LS_Mat_CoKinh_MatPhai { get; set; }
        public string LS_Mat_CoKinh_MatTrai { get; set; }
        public string LS_TaiMuiHong { get; set; }
        public string LS_TaiMuiHong_PhanLoai { get; set; }
        public string LS_TaiMuiHong_TaiTraiNoiTham { get; set; }
        public string LS_TaiMuiHong_TaiTraiNoiThuong { get; set; }
        public string LS_TaiMuiHong_TaiPhaiNoiTham { get; set; }
        public string LS_TaiMuiHong_TaiPhaiNoiThuong { get; set; }
        public string LS_TaiMuiHong_BacSiKham { get; set; }
        public string LS_RangHamMat { get; set; }
        public string LS_RangHamMat_PhanLoai { get; set; }
        public string LS_RangHamMat_BacSi { get; set; }
        public string CLS_XetNghiemMau_SoLuongHC { get; set; }
        public string CLS_XetNghiemMau_BachCau { get; set; }
        public string CLS_XetNghiemMau_TieuCau { get; set; }
        public string CLS_XetNghiemMau_DuongMau { get; set; }
        public string CLS_XetNghiemMau_Khac { get; set; }
        public string CLS_XetNghiemNuocTieu_Duong { get; set; }
        public string CLS_XetNghiemNuocTieu_Protein { get; set; }
        public string CLS_XetNghiemNuocTieu_Khac { get; set; }
        public Nullable<bool> CLS_ChanDoanHinhAnh_XQuangTimPhoi_BinhThuong { get; set; }
        public string CLS_ChanDoanHinhAnh_XQuangTimPhoi_CuThe { get; set; }
        public string CLS_ChanDoanHinhAnh_XQuangTimPhoi_Khac { get; set; }
        public string CLS_NguoiGhiKetQua { get; set; }
        public Nullable<bool> KL_KhoeManh { get; set; }
        public string KL_TenBenh { get; set; }
        public string KL_DatSucKhoeLoai { get; set; }
        public Nullable<bool> KL_DuDieuKienSucKhoe { get; set; }
        public string KL_MoTa { get; set; }
    
        public virtual T_NhanVien T_NhanVien { get; set; }
    }
}
