//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PhieuNhap_ChiTiet
    {
        public int ID { get; set; }
        public int MaPhieuNhap { get; set; }
        public Nullable<int> STT { get; set; }
        public int MaThietBi { get; set; }
        public decimal SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual T_PhieuNhap T_PhieuNhap { get; set; }
    }
}
