//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TocKy
    {
        public int ID { get; set; }
        public Nullable<short> Loai { get; set; }
        public Nullable<int> STT { get; set; }
        public string KyHieu { get; set; }
        public string NoiDung { get; set; }
    }
}
